# Generated by Django 4.0.6 on 2022-07-30 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student_homework',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('day2_work', models.TextField()),
                ('day1_work', models.TextField()),
                ('today_work', models.TextField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
