# Generated by Django 4.0.6 on 2022-07-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_homework',
            name='day1_work',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student_homework',
            name='day2_work',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='student_homework',
            name='today_work',
            field=models.TextField(null=True),
        ),
    ]
