# Generated by Django 4.1 on 2022-08-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='fee_initiated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='paid_date',
            field=models.DateTimeField(null=True),
        ),
    ]
