# Generated by Django 4.1 on 2022-08-20 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_studentfee_fee_initiated_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentfee',
            old_name='status',
            new_name='paid_status',
        ),
    ]
