# Generated by Django 4.1 on 2022-08-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_rename_status_studentfee_paid_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='fee_date',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
