# Generated by Django 4.1 on 2022-08-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_studentfee_fee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='fee_amount',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
    ]
