# Generated by Django 4.1 on 2022-08-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_studentfee_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_homework',
            name='username',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
