# Generated by Django 4.1 on 2022-09-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_student_homework_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='fee_initiated_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
