# Generated by Django 4.0.6 on 2022-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_userauthentication_is_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauthentication',
            name='is_parent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userauthentication',
            name='is_teacher',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
